# Seed box login name
    seedbox_login: "username"
# seedbox password
    seedbox_pw: "password"
# seedbox address
    seedbox_addr: "XXXX@seedbox.io"
# directory for managing torrents
    torrent_dir: "/place/to/where/torrent/files/should/go"
# place where .torrent files land (likely your DL folder)
    target_dir: "/downloads/"
